# ============================================================================
# TRAEFIK - REVERSE PROXY & SSL TERMINATION
# High Availability Docker Swarm Stack
# ============================================================================

version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-public
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=aifocusdev@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.aifocus.dev`)
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls.certresolver=letsencrypt
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080

volumes:
  traefik-letsencrypt:

networks:
  traefik-public:
    external: true

volumes:
  traefik-data:
    driver: local
  traefik-ssl:
    driver: local

configs:
  traefik-config:
    file: ./configs/traefik.yml
  traefik-dynamic:
    file: ./configs/traefik-dynamic.yml

secrets:
  cloudflare-token:
    external: true

# ============================================================================
# TRAEFIK DYNAMIC CONFIGURATION
# ============================================================================