version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11
    volumes:
      - uptime_data:/app/data
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.uptime.rule=Host(`uptime.aifocus.dev`)
        - traefik.http.routers.uptime.entrypoints=websecure
        - traefik.http.routers.uptime.tls.certresolver=letsencrypt
        - traefik.http.services.uptime.loadbalancer.server.port=3001

volumes:
  uptime_data:

networks:
  traefik-public:
    external: true 